@startuml

title Drupal 7 Standard Install\nContent Type Basic Page\nBundles Simplified ERD

hide circles
hide empty methods

!define KEY <color #D4AF37><U+1F511></color>
!define INDEX <color #888888><U+1F5C2></color>
!define FK <color #228B22><U+2192></color>

package "node.page bundle" {

  entity "node" {
    * KEY nid
    * type : 'page'
    * title
  }

  entity "field_data_body" {
    * KEY entity_type : 'node'
    * KEY entity_id : FK node.nid
    * bundle : 'page'
    * body_value
  }

}

node ||--|| field_data_body

package "comment.comment_node_page bundle" {

  entity "comment" {
    * KEY cid
    * nid : FK node.nid
    * subject
  }

  entity "field_data_comment_body" {
    * KEY entity_type : 'comment'
    * KEY entity_id : FK comment.cid
    * bundle : 'comment_node_page'
    * comment_body_value
  }

  comment ||--|| field_data_comment_body
  comment }o--|| node
}


@enduml
